[build]
    
    # publish = "views" 
    
[functions]

    directory = "netlify/functions" 


[[redirects]]
    # Перехоплюємо весь трафік
    from = "/*"
    
    to = "/.netlify/functions/server"
    
    status = 200